http://some.gitlab.yoursite.com/api/v3/projects:
  pz-idam:
    github: https://github.com/venicegeo/pz-idam
    gitlabgid: 2
  pz-sak:
    github: https://github.com/venicegeo/pz-sak
    gitlabgid: 2
http://another.gitlab.yoursite.com/api/v3/projects:
  bf-ui:
    github: https://github.com/venicegeo/bf-ui
    gitlabgid: 3
  bf-tideprediction:
    github: https://github.com/venicegeo/bf-tideprediction
    gitlabgid: 3
    # visibility is optional and can be 0 for private 10 for internal
    # or 20 for public. In newer versions of gitlab, the api
    # uses strings instead of integers for this value
    visibility: 10

